### ISSUE TITLE
Only home page has sidebar and title

### ISSUE THREAD

**Issue by honzik20** [gwatts/mostlydocs#1]
When I build your site locally, the home page has a sidebar and a title - but all the other pages don't. Any idea why?

**Comment by gwatts** [comment]
@honzik20 Which version of Hugo are you using?  It'll need to be at least 0.77.0 for it to work correctly

**Comment by honzik20** [comment]
Working for me now with

cascade:
  type: "docs"

Thank you

**Comment by gwatts** [comment]
Great, thanks for the update @honzik20 - Is there something i should improve/fix in the documentation?
